# START:diagnostics
# START:scheduler
# START:resque
extensions:
  diagnostics:
  # END:diagnostics
  scheduler:
  # END:scheduler
  resque:
    queues: critical, normal, low
    count:  1
    redis_host: 'localhost:6379'
    path: 'lib/workers'
  # END:resque